/*
 * Copyright 2026 Graham Lynch
 * SPDX-License-Identifier: Apache-2.0
 */
package io.github.glynch.jscene3d.editor.workbench.inspector;

import io.github.glynch.jscene3d.editor.presentation.AuthoringText;
import java.util.List;
import java.util.Objects;

/** Immutable typed Inspector projection independent of UI controls and callbacks.
 *
 * @param target stable semantic target
 * @param title author-facing title
 * @param definitionOrigin origin of the retained containing definition
 * @param provenance whether the target is local or realized through a placement
 * @param editable whether the target supports mutations
 * @param sections typed sections in declaration order
 */
public record InspectorProjection(
        InspectorTarget target,
        AuthoringText title,
        DefinitionOrigin definitionOrigin,
        Provenance provenance,
        boolean editable,
        List<InspectorSection> sections) {
    /** Copies and validates projected Inspector data. */
    public InspectorProjection {
        Objects.requireNonNull(target, "target");
        Objects.requireNonNull(title, "title");
        Objects.requireNonNull(definitionOrigin, "definitionOrigin");
        Objects.requireNonNull(provenance, "provenance");
        sections = List.copyOf(sections);
    }

    /** Retained-definition origin independent of occurrence provenance and editability. */
    public enum DefinitionOrigin {
        /** Definition was discovered in the authored project catalog. */
        AUTHORED,
        /** Definition was generated by imported or published content. */
        GENERATED
    }

    /** Selected occurrence provenance independent of containing definition origin. */
    public enum Provenance {
        /** Occurrence is authored directly in the retained definition. */
        LOCAL,
        /** Occurrence is realized beneath a reusable-definition placement. */
        GENERATED
    }
}
